Simple vector graphic editor: GUIController Class Reference
GUIController Class Reference
Interface between user and vector graphic editor.
#include <GUIController.hpp>
Public Member Functions
void createNewDocument ()
void importDocument (std::string filename)
void exportDocument (std::string filename)
void createPrimitive (int x, int y)
void deletePrimitive (int index)
Private Attributes
std::shared_ptr< GUIModel > model
GUIView view
Detailed Description
Interface between user and vector graphic editor.
GUIController class which is the main part of vector graphic editor. Works both with GUIModel and GUIView and has required features like creating new document, importing document from file, exporting document to a file, creating and deleteing primitives.
Works with only Point, just for the demo purposes.
Definition at line 18 of file GUIController.hpp.
Member Function Documentation
createNewDocument()
void GUIController::createNewDocument ()
Definition at line 3 of file GUIController.cpp.
References model.
Referenced by main().
createPrimitive()
void GUIController::createPrimitive (int x, int y)
Definition at line 28 of file GUIController.cpp.
References model, GUIView::show(), and view.
Referenced by main().
deletePrimitive()
void GUIController::deletePrimitive (int index)
Definition at line 34 of file GUIController.cpp.
References model, GUIView::show(), and view.
exportDocument()
void GUIController::exportDocument (std::string filename)
Definition at line 18 of file GUIController.cpp.
References model.
Referenced by main().
importDocument()
void GUIController::importDocument (std::string filename)
Definition at line 8 of file GUIController.cpp.
References model.
Member Data Documentation
model
std::shared_ptr<GUIModel> GUIController::model private
Definition at line 32 of file GUIController.hpp.
Referenced by createNewDocument(), createPrimitive(), deletePrimitive(), exportDocument(), and importDocument().
view
GUIView GUIController::view private
Definition at line 33 of file GUIController.hpp.
Referenced by createPrimitive(), and deletePrimitive().
The documentation for this class was generated from the following files:
GUIController.hpp
GUIController.cpp